[core]
server = "https://localhost"
polling = false
polling_sec = 10

[device]
uuid = "e8f83efb-c80c-45b3-80d9-80c98543015f"
system_info = "system_info.sh"
packages_dir = "/tmp/"
package_manager = "deb"
certificates_path = "/etc/sota_certificates"

[gateway]
console = false
dbus = false
http = false
rvi = true
socket = false
websocket = false

[rvi]
client = "http://127.0.0.1:8901"
storage_dir = "/var/sota"
timeout = 20

[dbus]
name = "org.genivi.SotaClient"
path = "/org/genivi/SotaClient"
interface = "org.genivi.SotaClient"
software_manager = "org.genivi.SoftwareLoadingManager"
software_manager_path = "/org/genivi/SoftwareLoadingManager"
timeout = 60

