apiVersion: v1
kind: Service
metadata:
  name: core
spec:
  ports:
  - port: 8080
  selector:
    app: core
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: core
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: core
    spec:
      containers:
      - image: advancedtelematic/sota-core
        name: core
        env:
        - name: BIND_HOST
          value: 0.0.0.0
        - name: CORE_DB_URL
          value: jdbc:mariadb://mysql.default.svc.cluster.local:3306/sota_core
        - name: CORE_INTERACTION_PROTOCOL
          value: none
        - name: DB_MIGRATE
          value: 'true'
        - name: DEVICE_REGISTRY_HOST
          value: 'device-registry.default.svc.cluster.local'
        - name: DEVICE_REGISTRY_PORT
          value: '8083'
        - name: KAFKA_HOST
          value: "kafka.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC_SUFFIX
          value: sota
        - name: MESSAGING_MODE
          value: kafka
        - name: SOTA_RESOLVER_HOST
          value: 'resolver.default.svc.cluster.local'
        - name: SOTA_RESOLVER_PORT
          value: '8081'
        - name: PACKAGES_VERSION_FORMAT
          value: .+
        - name: DB_ALIVE_URL
          value: 'mysql.default.svc.cluster.local:3306'
        - name: AUTH_PROTOCOL
          value: none
        ports:
        - containerPort: 8080
          name: core
