kind: Service
apiVersion: v1
metadata:
  name: device-registry
spec:
  selector:
    app: device-registry
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8083
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: device-registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: device-registry
    spec:
      containers:
      - name: device-registry
        image: advancedtelematic/sota-device_registry
        ports:
        - name: device-registry
          containerPort: 8083
        env:
        - name: BIND_HOST
          value: 0.0.0.0
        - name: DEVICE_REGISTRY_DB_URL
          value: jdbc:mariadb://mysql.default.svc.cluster.local:3306/sota_device_registry
        - name: DB_MIGRATE
          value: 'true'
        - name: KAFKA_HOST
          value: "kafka.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC_SUFFIX
          value: sota
        - name: MESSAGING_MODE
          value: kafka
        - name: DB_ALIVE_URL
          value: 'mysql.default.svc.cluster.local:3306'
        - name: AUTH_PROTOCOL
          value: none
