apiVersion: v1
kind: Service
metadata:
  name: ldap
spec:
  ports:
  - port: 9389
  selector:
    app: ldap
  clusterIP: None
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: ldap
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - image: advancedtelematic/openldap:genivi
        name: ldap
        command:
          - "--loglevel debug"
        ports:
        - containerPort: 389
          name: ldap
