apiVersion: v1
kind: Service
metadata:
  name: webserver
spec:
  ports:
  - port: 9000
  selector:
    app: webserver
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webserver
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
      - image: advancedtelematic/sota-webserver
        name: webserver
        env:
        - name: BIND_HOST
          value: 0.0.0.0
        - name: SOTA_CORE_HOST
          value: 'core.default.svc.cluster.local'
        - name: SOTA_CORE_PORT
          value: '8080'
        - name: DEVICE_REGISTRY_HOST
          value: 'device-registry.default.svc.cluster.local'
        - name: DEVICE_REGISTRY_PORT
          value: '8083'
        - name: KAFKA_HOST
          value: "kafka.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC_SUFFIX
          value: sota
        - name: MESSAGING_MODE
          value: kafka
        - name: SOTA_RESOLVER_HOST
          value: 'resolver.default.svc.cluster.local'
        - name: SOTA_RESOLVER_PORT
          value: '8081'
        - name: PLAY_CRYPTO_SECRET
          value: "YM5B6o<ywKn4tTyA;tOZ<2xUEajF4DDi=O/PPm1Q^w2LqtKISd9oqYT6b>>C1gQa"
        - name: LDAP_HOST
          value: "ldap.default.svc.cluster.local"
        - name: LDAP_PORT
          value: "389"
        - name: LDAP_AUTHN_ID
          value: "cn=admin,dc=genivi,dc=org"
        - name: LDAP_PASSWORD
          value: "admin"
        ports:
        - containerPort: 9000
          name: webserver
