version: '2'
services:

  rvi_device:
    image: advancedtelematic/rvi:latest
    network_mode: 'host'
    stdin_open: true
    depends_on:
      - rvi_backend
    expose:
      - 8901
    ports:
      - 8901:8901
    command: device
    environment:
      DEVICE_ID: 24b04cdd-1410-43f0-8690-ca8fac1ccd58
      RVI_BACKEND: "localhost"
      RVI_LOGLEVEL: debug
